### ISSUE TITLE
how to deploy to wp.org

### ISSUE THREAD

**Issue by cfoellmann** [blueglassdigital/job-postings#17]
@blueglassdigital how do you deploy to wordpress.org SVN?
This is always a pain and tried to find the best solution multiple times.

Lets use GitHub actions. Potential solutions:

- https://10up.com/blog/2019/introducing-github-actions-for-wordpress-plugins/ | https://github.com/10up/actions-wordpress/

- https://github.com/lubusIN/actions/tree/master/wordpress

**Comment by blueglassdigital** [comment]
Doing this the oldfashined way :D 

Will check about the github actions closer, thank you!

**Comment by cfoellmann** [comment]
Moved into #37
