### ISSUE TITLE
GDPR: Uploaded files are publicly available

### ISSUE THREAD

**Issue by cfoellmann** [blueglassdigital/job-postings#2]
uploads are being saved to the standard uploads folder.
All applications can be accessed publicly!!! Extreme risk

## OPTION B
authenticate downloads via php
https://wordpress.stackexchange.com/questions/37144/how-to-protect-uploads-if-user-is-not-logged-in
https://gist.github.com/hakre/1552239

**Comment by blueglassdigital** [comment]
@cfoellmann hey, what you think about storing files outside of the root directory?
Wouldnt this be much more widly supported by the servers, other than messing with the rewrites for apache, nginx, win servers... ?
What you think?

**Comment by blueglassdigital** [comment]
@cfoellmann gave it a try, pushed it to the development branch. Please test it on your end when have time. Also maybe you have somethign to add/change there.

**Comment by cfoellmann** [comment]
I did test this and it is a good start. Everything feels safe and secure.
But if you use this https://github.com/blueglassdigital/job-postings/commit/674f500f06323f159dab131dfd6e5819e570eb3e code your site will be blocked for all not-logged in users.

The path to get the files securely is getting into all requests.
Already tried re-saving the permalinks.
I will have alook now.

**Comment by cfoellmann** [comment]
Requiring auth was before detecting a request for a file. So it was forcing auth for ALL requests.
https://github.com/blueglassdigital/job-postings/commit/51d44a1b7a1103f1f7360eea9bc3fcd37aa2ca7c fixes this and it seems the "feature" is ready to merge and release.

**Comment by cfoellmann** [comment]
NOT ready, yet.
All the files will be added to the Media Browser!
Also the files are not being removed from the server (and the media browser) when the entries are deleted.

**Comment by blueglassdigital** [comment]
Hi @cfoellmann where's the issue exactly?
Is it here: https://github.com/blueglassdigital/job-postings/blob/f7e5a83d0c323c747b0b57f7bd0aaf320279ae93/include/class-job-application-submit.php#L500-L505 ??

**Comment by blueglassdigital** [comment]
And right, will add deletion of the files with "delete_post" or "before_delete_post" hook.

**Comment by blueglassdigital** [comment]
@cfoellmann it seems the WPML was the problem of deleting all files from media. But I fixed it the other way around.

**Comment by blueglassdigital** [comment]
@cfoellmann Releasing the updates

**Comment by blueglassdigital** [comment]
@cfoellmann also added the option to switch between "secure" and legacy way of string uploaded files. As seems "out of the root" directory don't work on some hosting, like wp.com for example. 
(Had email support request)
