### ISSUE TITLE
Typo breaking stuff?

### ISSUE THREAD

**Issue by cfoellmann** [blueglassdigital/job-postings#38]
@blueglassdigital can your have a quick look at https://github.com/blueglassdigital/job-postings/blob/master/include/shortcodes/class-job-list.php#L114 to determine if the typo in the variable breaks something?
I dont habe the time at the moment to test stuff properly

**Comment by blueglassdigital** [comment]
@cfoellmann typo in "hide_past" you mean? tried with "hidepast" and "hide-past". Doent break for me

**Comment by cfoellmann** [comment]
I was wrong. I dont know what I saw there.
Sorry for that.
