### ISSUE TITLE
Notification e-mail from address is not applicant e-mail

### ISSUE THREAD

**Issue by cdefy** [blueglassdigital/job-postings#44]
Hi,

First thank you a lot for your plugin, I tried different ones on WordPress and yours seem to be the most complete.

I'm just facing a really annoying issue, when I receive an application notification, the from e-mail is my own so:
- I don't know who wrote to me unless I open the e-mail (but with multiple e-mails received I'm just lost)
- If I reply to the application, I'm actually replying to myself!

This bug was flagged in WordPress support forum more than a year ago:
[notification e-mail](https://wordpress.org/support/topic/notification-e-mail/)

I know it's an open-source and free plugin, you're probably doing your best to maintain it but this old issue seems kind of urgent for a job application plugin ;)
Thanks in advance for your time!

EDIT: I was checking the version and seems that it supposed to have been fixed in 2.1.2:  "Fixed email address in entry email to reply directly to sender."

**Comment by infazz** [comment]
@cdefy 
Please try the updated version of the plugin.
Also please keep in mind that most of the SMTP plugins rewrite the "from" email... But "reply-to" seem now stay properly, so you can reply to candidate directly now again :)

Br

**Comment by cdefy** [comment]
@infazz Awesome guys! The "from" name is the name of applicant and the "reply-to" is working. Thank you a lot, it makes it much easier to have applicant name in list of e-mails instead of our company name!

If I may, we added a first name field because last name only can be confusing sometimes, I though it could be a good idea to have this field by default and use it with the name in the "from" string. But that's an enhancement ;)

Thank to you and all your team (had a chat by e-mail), really appreciated the time you took to fix that annoying bug and your reactivity.

@cfoellmann Thanks for your help also ;)

**Comment by cdefy** [comment]
@infazz Hi!

There might be a regression on the last update, e-mail notification doesn't have attachments any more (CV), but CV are in WP admin pannel applications.
Last e-mail with attachment: 9/06 21h, first e-mail without attachment: 10/06 10h23, it's when I did the plugin update and send a test e-mail.

Thank you in advance if you can have a look.
Cheers

**Comment by cdefy** [comment]
Regression fixed in last update, thanks @infazz !
